version: '3'

services:
  nodejs:
    container_name: nodejs
    build:
      context: .
      target: development
      dockerfile: docker/Dockerfile.development
    command: yarn start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - application-network
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - application-network
    restart: always
    env_file:
      - .env

volumes:
  postgres-volume:

networks:
  application-network:
    driver: bridge
